### PR TITLE
Adding caching for crowd tokens.

### PR DESCRIPTION
**Pull request by mrmateo**
Also fixed a small spelling mistake.

### CODE REVIEW

**Comment by mrmateo** [comment]
Found that this helps reduce excessive crowd calls during high usage times.

**Comment by pingunaut** [comment]
Hi @mrmateo,
Thanks a lot for your input. Looks good to me. However, there is one change to the existing logic as far as I understand:
Until now, only user and group data is cached. Authentication/validation calls are not. 
With your change implemented, the token validation result will also be cached.
Users will be able to authenticate until their validation result is removed from the cache. This will also work if a Crowd administrator has revoked Jenkins access for that user meanwhile.

Is this correct or am I missing something?

**Comment by mrmateo** [comment]
Good questions, responses inline:
> Users will be able to authenticate until their validation result is removed from the cache.

Correct, their SSO token will be active until it has expired from the cache, which would then either get re-validated by another call to the Crowd server or not (depending if they're logged out or had their token be expired by the remote server). 

> This will also work if a Crowd administrator has revoked Jenkins access for that user meanwhile.

I don't believe that is accurate. This part of the process is only validating their authentication token (i.e. verifying who they are). It sounds like you're specifically referring to authorization (i.e. can they access this resource)? Authorization would occur later in the process after Jenkins has obtained all of the user information and compares it with local policies. 

Re-looking at the code, I had meant to have this use the session validation interval (multiplied out to seconds) instead of the cache ttl for defining the cache duration. I can update that but let me know if you have any additional questions or concerns.

Thanks.

**Comment by pingunaut** [comment]
I just had a look the help text provided on the administration page and found that we already added a warning about delayed change propagation.
> Some Crowd servers may be slow, or rate limit client requests. In such cases enabling caching may improve performance of Jenkins with the risk of delayed propagation of user changes from Crowd and increased memory usage on the master.
Note: The default configuration is to leave the cache turned off.

@daniel-beck you helped me with a security related issue earlier, maybe you can share your opinion on this PR? Is it OK to cache the authentication result to gain performance/reduce remote server load?
This implies that users can successfully authenticate during the caching period, although a Crowd administrator revoked the users access meanwhile.

**Comment by DuMaM** [comment]
Hi @mrmateo,
Thanks for this PR, I really appreciate it.
Could you update your branch against recent changes?

**Comment by mrmateo** [comment]
Code has been rebased to latest upstream commits.

**Comment by DuMaM** [comment]
@mrmateo Please create feature branch on your fork. Do not create PR's form master branch.

**Comment by DuMaM** [comment]
Also some test will be welcome :)

**Comment by DuMaM** [comment]
closed in favour of https://github.com/jenkinsci/crowd2-plugin/pull/169

**Pull request closed without merging**
