### PR TITLE
Reimplementation of missing methods with atlassian-crowd-rest-client …

### PR DESCRIPTION
**Pull request by msglueck**
…and jaxb plugin binding. Sadly running out of time ATM. Think it's a step closer but still some major gaps to succeed. Especially tests need to be also improved. Still getting the JAXB errors:

javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.

`Caused: javax.xml.bind.DataBindingException: Cannot instantiate JAXBContext for class class com.atlassian.crowd.integration.rest.entity.ValidationFactorEntityList
	at com.atlassian.crowd.integration.rest.util.JAXBContextCache.getJAXBContext(JAXBContextCache.java:61)
	at com.atlassian.crowd.integration.rest.service.RestExecutor.getMarshaller(RestExecutor.java:414)`

### CODE REVIEW

**Comment by alwynpan** [comment]
Tried with `2.303.1`, this fix is no longer working.

**Comment by ricksbrown** [comment]
This looks like a >JDK11 issue and should be resolved by the changes in #40

**Comment by DuMaM** [comment]
@msglueck Please update your branch

**Comment by DuMaM** [comment]
I know a bit better this plugin now and I would say that this approach is not recommended one.
You basically replaced rest java crowd api with java crowd api, which is less stable.
I would like to stick with rest api, because it do not change so much as non rest one.

**Pull request closed without merging**
