### PR TITLE
Refactor, fixes REMEMBERME support, makes right AUTH design/work

### PR DESCRIPTION
**Pull request by KostyaSha**
Refactoring of plugin, because it was bad idea binding SSO into Remember Me that ends in not working remember me. New implementation uses best practises and almost the same spring-security implementation.

[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/crowd2-plugin/9)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@aheritier afair the main problem was with checking that authenticated token is valid and authorisation should silently accept...
My old question was here https://jira.atlassian.com/browse/CWD-4063

**Comment by KostyaSha** [comment]
Code of course dirty, but i need working skeleton first. User reported that for non-SSO configuration rememberme works right. SSO part is still an issue If this issue will be resolved, then i'm happy finally refactor coding style and accept here your changes without coding style cleanups.

**Comment by KostyaSha** [comment]
First of all we need ATH test with crowd2 and i.e. jira containers linked. 
- Test for auth without sso
- Tets with auth using SSO
  - auth is done on jira and jenkins logged in automatically (wasn't logged before)
 - auth is done on jenkins and jira will be logged in

Problem will be hostnames as they are required for SSO

**Comment by KostyaSha** [comment]
I started creating containers and test. If somebody wants help, then i will be very glad

**Comment by KostyaSha** [comment]
@aheritier i bit cleaned-up code and reviewed almost all classes. Fixed code and verified that it works right with user/password login with and without Remember Me. 
I created docker and described how it can be used https://github.com/KostyaSha/docker-centos-crowd also searching ways create good ATH/JenkinsRule tests but everywhere they have problems https://groups.google.com/forum/#!topic/jenkinsci-dev/R2_tHJDF0KI

**Comment by KostyaSha** [comment]
@aheritier don't try follow commits, just open code :) The main problem now to manage SSO routines. (Probably servlet filter + Provider)

**Comment by KostyaSha** [comment]
@aheritier and FYI your custom caching probably redundant, it should be enough to use built-in ehcache https://confluence.atlassian.com/display/CROWD/Configuring+Caching+for+an+Application

**Comment by aheritier** [comment]
Great work @KostyaSha I will review test it. About the default/ehcache configuration it may be a good thing if we can allow to externalise its configuration. I'll have a look at it when we'll work to rewrite my cache implementation.

**Comment by KostyaSha** [comment]
@recena do you still want help? @aheritier is very busy, i can guide what to do.

**Comment by recena** [comment]
@KostyaSha I'm interesting on help here.

**Comment by KostyaSha** [comment]
@recena what do you need to start with? Any guide/steps? Really want end this change.

**Comment by recena** [comment]
@KostyaSha Time. I'm really want to help here but I need to cut some releases (plugins) before.

**Comment by DukeHarris** [comment]
Any updates here? It's been more than half a year since the last commit/comment. It would be really nice to have remember me working. My Developers basically complain daily about having to enter their credentials every time they close their browser.

**Comment by KostyaSha** [comment]
Nobody helped with making the last step in making all auth how it should work. Upgrade from acegi-security was also rejected in 2.0. As maintainer i can say that i would better create separate plugin based on my full rewrote/refactor code. So i can left this plugin as i didn't have any crowd instances now.

**Comment by hypery2k** [comment]
@KostyaSha Did you released a separate plugin?

**Comment by testuser7** [comment]
There is crowd-ldap-server plugin that delegates LDAP requests to Crowd: https://github.com/dwimberger/crowd-ldap-server
Anyone tried to use with Jenkins?

**Comment by KostyaSha** [comment]
> @KostyaSha Did you released a separate plugin?

No. 
The root of all issues is absent spring-security instead of acegi-security.

**Comment by hypery2k** [comment]
i have now write access to the repo and will try to check your fork against a crowd server

**Comment by hypery2k** [comment]
@KostyaSha Can you add me as editor?

**Pull request closed without merging**
